/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidex_MainActivity */

#ifndef _Included_com_example_androidex_MainActivity
#define _Included_com_example_androidex_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_androidex_MainActivity
 * Method:    openDevice
 * Signature: (Lcom/example/androidex/MainActivity/Args;)I
 */
JNIEXPORT jint JNICALL Java_com_example_androidex_MainActivity_openDevice
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_example_androidex_MainActivity
 * Method:    closeDevice
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_androidex_MainActivity_closeDevice
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
